/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'priceCents' : IDL.Nat,
});
export const Cart = IDL.Record({
  'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const Customer = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'pickupAddress' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Record({
    'amountCents' : IDL.Nat,
    'timestamp' : Time,
    'sessionId' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'reason' : IDL.Text }),
});
export const PaymentMethod = IDL.Variant({
  'stripe' : IDL.Null,
  'cashOnDelivery' : IDL.Null,
});
export const OrderTrackingEntry = IDL.Record({
  'status' : OrderStatus,
  'note' : IDL.Text,
  'timestamp' : Time,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'customer' : IDL.Principal,
  'tracking' : IDL.Vec(OrderTrackingEntry),
  'totalPriceCents' : IDL.Nat,
  'pickupTime' : IDL.Opt(Time),
  'timestamp' : Time,
  'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'checkUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [Product],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getCatalogMetadata' : IDL.Func(
      [],
      [IDL.Record({ 'productCount' : IDL.Nat })],
      ['query'],
    ),
  'getCustomerByPrincipal' : IDL.Func([IDL.Principal], [Customer], ['query']),
  'getIdForCaller' : IDL.Func([], [IDL.Principal], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductImage' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
  'grantUserRole' : IDL.Func([IDL.Principal], [], []),
  'initialize' : IDL.Func([], [], []),
  'initializeAdminAccess' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isAdminConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProducts' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Product)], ['query']),
  'markOrderAsPaidAdmin' : IDL.Func([IDL.Nat], [], []),
  'placeOrder' : IDL.Func([PaymentMethod, IDL.Opt(Time)], [IDL.Nat], []),
  'registerCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'revokeAdminRole' : IDL.Func([IDL.Principal], [], []),
  'setOrderCompleted' : IDL.Func([IDL.Nat], [], []),
  'setOrderPaid' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [Product],
      [],
    ),
  'uploadProductImage' : IDL.Func([IDL.Nat, ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'priceCents' : IDL.Nat,
  });
  const Cart = IDL.Record({ 'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)) });
  const Customer = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'pickupAddress' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Record({
      'amountCents' : IDL.Nat,
      'timestamp' : Time,
      'sessionId' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'reason' : IDL.Text }),
  });
  const PaymentMethod = IDL.Variant({
    'stripe' : IDL.Null,
    'cashOnDelivery' : IDL.Null,
  });
  const OrderTrackingEntry = IDL.Record({
    'status' : OrderStatus,
    'note' : IDL.Text,
    'timestamp' : Time,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'customer' : IDL.Principal,
    'tracking' : IDL.Vec(OrderTrackingEntry),
    'totalPriceCents' : IDL.Nat,
    'pickupTime' : IDL.Opt(Time),
    'timestamp' : Time,
    'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'checkUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [Product],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getCatalogMetadata' : IDL.Func(
        [],
        [IDL.Record({ 'productCount' : IDL.Nat })],
        ['query'],
      ),
    'getCustomerByPrincipal' : IDL.Func([IDL.Principal], [Customer], ['query']),
    'getIdForCaller' : IDL.Func([], [IDL.Principal], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductImage' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
    'grantUserRole' : IDL.Func([IDL.Principal], [], []),
    'initialize' : IDL.Func([], [], []),
    'initializeAdminAccess' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isAdminConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProducts' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'markOrderAsPaidAdmin' : IDL.Func([IDL.Nat], [], []),
    'placeOrder' : IDL.Func([PaymentMethod, IDL.Opt(Time)], [IDL.Nat], []),
    'registerCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'revokeAdminRole' : IDL.Func([IDL.Principal], [], []),
    'setOrderCompleted' : IDL.Func([IDL.Nat], [], []),
    'setOrderPaid' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [Product],
        [],
      ),
    'uploadProductImage' : IDL.Func(
        [IDL.Nat, ExternalBlob],
        [ExternalBlob],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };