/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'priceCents' : IDL.Nat,
});
export const Cart = IDL.Record({
  'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});
export const Customer = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'pickupAddress' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'canceled' : IDL.Null,
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'totalPriceCents' : IDL.Nat,
  'pickupTime' : IDL.Opt(Time),
  'timestamp' : Time,
  'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [Product],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getCustomerByPrincipal' : IDL.Func([IDL.Principal], [Customer], ['query']),
  'getIdForCaller' : IDL.Func([], [IDL.Principal], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductImage' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProducts' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([IDL.Opt(Time)], [IDL.Nat], []),
  'registerCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [Product],
      [],
    ),
  'uploadProductImage' : IDL.Func([IDL.Nat, ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'priceCents' : IDL.Nat,
  });
  const Cart = IDL.Record({ 'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)) });
  const Customer = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'pickupAddress' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'canceled' : IDL.Null,
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'totalPriceCents' : IDL.Nat,
    'pickupTime' : IDL.Opt(Time),
    'timestamp' : Time,
    'items' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [Product],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getCustomerByPrincipal' : IDL.Func([IDL.Principal], [Customer], ['query']),
    'getIdForCaller' : IDL.Func([], [IDL.Principal], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductImage' : IDL.Func([IDL.Nat], [IDL.Opt(ExternalBlob)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProducts' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([IDL.Opt(Time)], [IDL.Nat], []),
    'registerCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [Product],
        [],
      ),
    'uploadProductImage' : IDL.Func(
        [IDL.Nat, ExternalBlob],
        [ExternalBlob],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };