/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cart { 'items' : Array<[bigint, bigint]> }
export interface Customer {
  'principal' : Principal,
  'name' : string,
  'pickupAddress' : string,
  'phoneNumber' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'customer' : Principal,
  'tracking' : Array<OrderTrackingEntry>,
  'totalPriceCents' : bigint,
  'pickupTime' : [] | [Time],
  'timestamp' : Time,
  'items' : Array<[bigint, bigint]>,
}
export type OrderStatus = { 'canceled' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface OrderTrackingEntry {
  'status' : OrderStatus,
  'note' : string,
  'timestamp' : Time,
}
export type PaymentMethod = { 'stripe' : null } |
  { 'cashOnDelivery' : null };
export type PaymentStatus = { 'pending' : null } |
  {
    'completed' : {
      'amountCents' : bigint,
      'timestamp' : Time,
      'sessionId' : string,
    }
  } |
  { 'failed' : { 'reason' : string } };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : [] | [ExternalBlob],
  'priceCents' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateAdmin' : ActorMethod<[string, string], undefined>,
  'checkUserRole' : ActorMethod<[Principal], UserRole>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createProduct' : ActorMethod<
    [string, string, bigint, string, [] | [ExternalBlob]],
    Product
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getCatalogMetadata' : ActorMethod<[], { 'productCount' : bigint }>,
  'getCustomerByPrincipal' : ActorMethod<[Principal], Customer>,
  'getIdForCaller' : ActorMethod<[], Principal>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductImage' : ActorMethod<[bigint], [] | [ExternalBlob]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'grantAdminRole' : ActorMethod<[Principal], undefined>,
  'grantUserRole' : ActorMethod<[Principal], undefined>,
  'initialize' : ActorMethod<[], undefined>,
  'initializeAdminAccess' : ActorMethod<[string, string], undefined>,
  'isAdminConfigured' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllProducts' : ActorMethod<[], Array<Product>>,
  'listProducts' : ActorMethod<[[] | [string]], Array<Product>>,
  'markOrderAsPaidAdmin' : ActorMethod<[bigint], undefined>,
  'placeOrder' : ActorMethod<[PaymentMethod, [] | [Time]], bigint>,
  'registerCustomer' : ActorMethod<[string, string, string], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'revokeAdminRole' : ActorMethod<[Principal], undefined>,
  'setOrderCompleted' : ActorMethod<[bigint], undefined>,
  'setOrderPaid' : ActorMethod<[bigint, string, bigint], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminCredentials' : ActorMethod<[string, string], undefined>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, [] | [ExternalBlob]],
    Product
  >,
  'uploadProductImage' : ActorMethod<[bigint, ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];